import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Georgian} from "next/font/google";
import "./globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansGeorgian = Noto_Sans_Georgian({
  variable: "--font-noto-sans-georgian",
  subsets: ["latin", "georgian"],
  weight: ["400", "500","600", "700"],
});

export const metadata: Metadata = {
  title: "AVSE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {process.env.NODE_ENV === 'production' && (
          <base href="/landingOfIncome/" />
        )}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${notoSansGeorgian.variable}`}>
        {children}
      </body>
    </html>
  );
}
